// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type AddStatusPageStatuspagesPostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	AddStatusPageResponse *shared.AddStatusPageResponse
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *AddStatusPageStatuspagesPostResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddStatusPageStatuspagesPostResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddStatusPageStatuspagesPostResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AddStatusPageStatuspagesPostResponse) GetAddStatusPageResponse() *shared.AddStatusPageResponse {
	if o == nil {
		return nil
	}
	return o.AddStatusPageResponse
}

func (o *AddStatusPageStatuspagesPostResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
