// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type DeleteUserUsersUsernameDeleteRequest struct {
	Username string `pathParam:"style=simple,explode=false,name=username"`
}

func (o *DeleteUserUsersUsernameDeleteRequest) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

type DeleteUserUsersUsernameDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	Any any
	// Not Found
	HTTPNotFoundError *shared.HTTPNotFoundError
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *DeleteUserUsersUsernameDeleteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteUserUsersUsernameDeleteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteUserUsersUsernameDeleteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteUserUsersUsernameDeleteResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *DeleteUserUsersUsernameDeleteResponse) GetHTTPNotFoundError() *shared.HTTPNotFoundError {
	if o == nil {
		return nil
	}
	return o.HTTPNotFoundError
}

func (o *DeleteUserUsersUsernameDeleteResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
