// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type DeleteTagTagsTagIDDeleteRequest struct {
	TagID int64 `pathParam:"style=simple,explode=false,name=tag_id"`
}

func (o *DeleteTagTagsTagIDDeleteRequest) GetTagID() int64 {
	if o == nil {
		return 0
	}
	return o.TagID
}

type DeleteTagTagsTagIDDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	Any any
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *DeleteTagTagsTagIDDeleteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteTagTagsTagIDDeleteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteTagTagsTagIDDeleteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteTagTagsTagIDDeleteResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *DeleteTagTagsTagIDDeleteResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
