// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type GetStatusPageStatuspagesSlugGetRequest struct {
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *GetStatusPageStatuspagesSlugGetRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type GetStatusPageStatuspagesSlugGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	StatusPage *shared.StatusPage
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *GetStatusPageStatuspagesSlugGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetStatusPageStatuspagesSlugGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetStatusPageStatuspagesSlugGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetStatusPageStatuspagesSlugGetResponse) GetStatusPage() *shared.StatusPage {
	if o == nil {
		return nil
	}
	return o.StatusPage
}

func (o *GetStatusPageStatuspagesSlugGetResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
