// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pete-leese/terraform-provider-ukumawapi/internal/sdk/internal/utils"
	"github.com/pete-leese/terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type MonitorBeatsMonitorsMonitorIDBeatsGetRequest struct {
	MonitorID int64    `pathParam:"style=simple,explode=false,name=monitor_id"`
	Hours     *float64 `default:"1" queryParam:"style=form,explode=true,name=hours"`
}

func (m MonitorBeatsMonitorsMonitorIDBeatsGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MonitorBeatsMonitorsMonitorIDBeatsGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MonitorBeatsMonitorsMonitorIDBeatsGetRequest) GetMonitorID() int64 {
	if o == nil {
		return 0
	}
	return o.MonitorID
}

func (o *MonitorBeatsMonitorsMonitorIDBeatsGetRequest) GetHours() *float64 {
	if o == nil {
		return nil
	}
	return o.Hours
}

type MonitorBeatsMonitorsMonitorIDBeatsGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	Any any
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *MonitorBeatsMonitorsMonitorIDBeatsGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MonitorBeatsMonitorsMonitorIDBeatsGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MonitorBeatsMonitorsMonitorIDBeatsGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MonitorBeatsMonitorsMonitorIDBeatsGetResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *MonitorBeatsMonitorsMonitorIDBeatsGetResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
