// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type PostIncidentStatuspagesSlugIncidentPostRequest struct {
	Slug                string                     `pathParam:"style=simple,explode=false,name=slug"`
	PostIncidentRequest shared.PostIncidentRequest `request:"mediaType=application/json"`
}

func (o *PostIncidentStatuspagesSlugIncidentPostRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *PostIncidentStatuspagesSlugIncidentPostRequest) GetPostIncidentRequest() shared.PostIncidentRequest {
	if o == nil {
		return shared.PostIncidentRequest{}
	}
	return o.PostIncidentRequest
}

type PostIncidentStatuspagesSlugIncidentPostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	PostIncidentResponse *shared.PostIncidentResponse
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *PostIncidentStatuspagesSlugIncidentPostResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostIncidentStatuspagesSlugIncidentPostResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostIncidentStatuspagesSlugIncidentPostResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostIncidentStatuspagesSlugIncidentPostResponse) GetPostIncidentResponse() *shared.PostIncidentResponse {
	if o == nil {
		return nil
	}
	return o.PostIncidentResponse
}

func (o *PostIncidentStatuspagesSlugIncidentPostResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
