// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type SaveStatusPageStatuspagesSlugPostRequest struct {
	Slug                  string                       `pathParam:"style=simple,explode=false,name=slug"`
	SaveStatusPageRequest shared.SaveStatusPageRequest `request:"mediaType=application/json"`
}

func (o *SaveStatusPageStatuspagesSlugPostRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *SaveStatusPageStatuspagesSlugPostRequest) GetSaveStatusPageRequest() shared.SaveStatusPageRequest {
	if o == nil {
		return shared.SaveStatusPageRequest{}
	}
	return o.SaveStatusPageRequest
}

type SaveStatusPageStatuspagesSlugPostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	SaveStatusPageResponse *shared.SaveStatusPageResponse
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *SaveStatusPageStatuspagesSlugPostResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SaveStatusPageStatuspagesSlugPostResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SaveStatusPageStatuspagesSlugPostResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SaveStatusPageStatuspagesSlugPostResponse) GetSaveStatusPageResponse() *shared.SaveStatusPageResponse {
	if o == nil {
		return nil
	}
	return o.SaveStatusPageResponse
}

func (o *SaveStatusPageStatuspagesSlugPostResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
