// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type UpdateMaintenanceMaintenanceMaintenanceIDPatchRequest struct {
	MaintenanceID     int64                    `pathParam:"style=simple,explode=false,name=maintenance_id"`
	MaintenanceUpdate shared.MaintenanceUpdate `request:"mediaType=application/json"`
}

func (o *UpdateMaintenanceMaintenanceMaintenanceIDPatchRequest) GetMaintenanceID() int64 {
	if o == nil {
		return 0
	}
	return o.MaintenanceID
}

func (o *UpdateMaintenanceMaintenanceMaintenanceIDPatchRequest) GetMaintenanceUpdate() shared.MaintenanceUpdate {
	if o == nil {
		return shared.MaintenanceUpdate{}
	}
	return o.MaintenanceUpdate
}

type UpdateMaintenanceMaintenanceMaintenanceIDPatchResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	Any any
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *UpdateMaintenanceMaintenanceMaintenanceIDPatchResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateMaintenanceMaintenanceMaintenanceIDPatchResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateMaintenanceMaintenanceMaintenanceIDPatchResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateMaintenanceMaintenanceMaintenanceIDPatchResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *UpdateMaintenanceMaintenanceMaintenanceIDPatchResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
