// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform-provider-ukumawapi/internal/sdk/models/shared"
	"net/http"
)

type UploadBackupSettingsUploadBackupPostRequest struct {
	// An enumeration.
	ImportHandle shared.ImportHandleType `queryParam:"style=form,explode=true,name=import_handle"`
	Backup       shared.Backup           `request:"mediaType=application/json"`
}

func (o *UploadBackupSettingsUploadBackupPostRequest) GetImportHandle() shared.ImportHandleType {
	if o == nil {
		return shared.ImportHandleType("")
	}
	return o.ImportHandle
}

func (o *UploadBackupSettingsUploadBackupPostRequest) GetBackup() shared.Backup {
	if o == nil {
		return shared.Backup{}
	}
	return o.Backup
}

type UploadBackupSettingsUploadBackupPostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful Response
	Any any
	// Validation Error
	HTTPValidationError *shared.HTTPValidationError
}

func (o *UploadBackupSettingsUploadBackupPostResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UploadBackupSettingsUploadBackupPostResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UploadBackupSettingsUploadBackupPostResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UploadBackupSettingsUploadBackupPostResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}

func (o *UploadBackupSettingsUploadBackupPostResponse) GetHTTPValidationError() *shared.HTTPValidationError {
	if o == nil {
		return nil
	}
	return o.HTTPValidationError
}
