// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AddStatusPageResponse struct {
	Msg *string `json:"msg,omitempty"`
}

func (o *AddStatusPageResponse) GetMsg() *string {
	if o == nil {
		return nil
	}
	return o.Msg
}
