// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/pete-leese/terraform-provider-ukumawapi/internal/sdk/internal/utils"
)

type BodyLoginAccessTokenLoginAccessTokenPost struct {
	GrantType    *string `form:"name=grant_type"`
	Username     string  `form:"name=username"`
	Password     string  `form:"name=password"`
	Scope        *string `default:"" form:"name=scope"`
	ClientID     *string `form:"name=client_id"`
	ClientSecret *string `form:"name=client_secret"`
}

func (b BodyLoginAccessTokenLoginAccessTokenPost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BodyLoginAccessTokenLoginAccessTokenPost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BodyLoginAccessTokenLoginAccessTokenPost) GetGrantType() *string {
	if o == nil {
		return nil
	}
	return o.GrantType
}

func (o *BodyLoginAccessTokenLoginAccessTokenPost) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *BodyLoginAccessTokenLoginAccessTokenPost) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *BodyLoginAccessTokenLoginAccessTokenPost) GetScope() *string {
	if o == nil {
		return nil
	}
	return o.Scope
}

func (o *BodyLoginAccessTokenLoginAccessTokenPost) GetClientID() *string {
	if o == nil {
		return nil
	}
	return o.ClientID
}

func (o *BodyLoginAccessTokenLoginAccessTokenPost) GetClientSecret() *string {
	if o == nil {
		return nil
	}
	return o.ClientSecret
}
