// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DeleteStatusPageResponse struct {
	// Error detail, if any
	Detail *string `json:"detail,omitempty"`
}

func (o *DeleteStatusPageResponse) GetDetail() *string {
	if o == nil {
		return nil
	}
	return o.Detail
}
