// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ImportHandleType - An enumeration.
type ImportHandleType string

const (
	ImportHandleTypeSkip      ImportHandleType = "skip"
	ImportHandleTypeOverwrite ImportHandleType = "overwrite"
	ImportHandleTypeKeep      ImportHandleType = "keep"
)

func (e ImportHandleType) ToPointer() *ImportHandleType {
	return &e
}
func (e *ImportHandleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "skip":
		fallthrough
	case "overwrite":
		fallthrough
	case "keep":
		*e = ImportHandleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ImportHandleType: %v", v)
	}
}
