// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Incident struct {
	Content         string  `json:"content"`
	CreatedDate     string  `json:"createdDate"`
	ID              int64   `json:"id"`
	LastUpdatedDate *string `json:"lastUpdatedDate,omitempty"`
	Pin             int64   `json:"pin"`
	Style           string  `json:"style"`
	Title           string  `json:"title"`
}

func (o *Incident) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

func (o *Incident) GetCreatedDate() string {
	if o == nil {
		return ""
	}
	return o.CreatedDate
}

func (o *Incident) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Incident) GetLastUpdatedDate() *string {
	if o == nil {
		return nil
	}
	return o.LastUpdatedDate
}

func (o *Incident) GetPin() int64 {
	if o == nil {
		return 0
	}
	return o.Pin
}

func (o *Incident) GetStyle() string {
	if o == nil {
		return ""
	}
	return o.Style
}

func (o *Incident) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}
