// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-ukumawapi/internal/sdk/internal/utils"
)

type JWToken struct {
	AccessToken string  `json:"access_token"`
	TokenType   *string `default:"Bearer" json:"token_type"`
}

func (j JWToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JWToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *JWToken) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *JWToken) GetTokenType() *string {
	if o == nil {
		return nil
	}
	return o.TokenType
}
