// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-ukumawapi/internal/sdk/internal/utils"
)

// Maintenance - Title (str) – Title.
//
// strategy (MaintenanceStrategy) – Strategy
//
// active (bool, optional) – True if maintenance is active, defaults to True
//
// description (str, optional) – Description, defaults to ""
//
// dateRange (list, optional) – DateTime Range, defaults to ["<current date>"]
//
// intervalDay (int, optional) – Interval (Run once every day), defaults to 1
//
// weekdays (list, optional) – List that contains the days of the week on which the maintenance is enabled (Sun = 0, Mon = 1, …, Sat = 6). Required for strategy RECURRING_WEEKDAY., defaults to [].
//
// daysOfMonth (list, optional) – List that contains the days of the month on which the maintenance is enabled (Day 1 = 1, Day 2 = 2, …, Day 31 = 31) and the last day of the month (Last Day of Month = "lastDay1", 2nd Last Day of Month = "lastDay2", 3rd Last Day of Month = "lastDay3", 4th Last Day of Month = "lastDay4"). Required for strategy RECURRING_DAY_OF_MONTH., defaults to [].
//
// timeRange (list, optional) – Maintenance Time Window of a Day, defaults to [{"hours": 2, "minutes": 0}, {"hours": 3, "minutes": 0}].
type Maintenance struct {
	Title string `json:"title"`
	// Enumerate maintenance strategies.
	Strategy    MaintenanceStrategy `json:"strategy"`
	Active      *bool               `default:"true" json:"active"`
	Description *string             `default:"" json:"description"`
	DateRange   []any               `json:"dateRange,omitempty"`
	IntervalDay *int64              `default:"1" json:"intervalDay"`
	Weekdays    []any               `json:"weekdays,omitempty"`
	DaysOfMonth []any               `json:"daysOfMonth,omitempty"`
	TimeRange   []any               `json:"timeRange,omitempty"`
}

func (m Maintenance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Maintenance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Maintenance) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *Maintenance) GetStrategy() MaintenanceStrategy {
	if o == nil {
		return MaintenanceStrategy("")
	}
	return o.Strategy
}

func (o *Maintenance) GetActive() *bool {
	if o == nil {
		return nil
	}
	return o.Active
}

func (o *Maintenance) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Maintenance) GetDateRange() []any {
	if o == nil {
		return nil
	}
	return o.DateRange
}

func (o *Maintenance) GetIntervalDay() *int64 {
	if o == nil {
		return nil
	}
	return o.IntervalDay
}

func (o *Maintenance) GetWeekdays() []any {
	if o == nil {
		return nil
	}
	return o.Weekdays
}

func (o *Maintenance) GetDaysOfMonth() []any {
	if o == nil {
		return nil
	}
	return o.DaysOfMonth
}

func (o *Maintenance) GetTimeRange() []any {
	if o == nil {
		return nil
	}
	return o.TimeRange
}
