// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// MaintenanceStrategy - Enumerate maintenance strategies.
type MaintenanceStrategy string

const (
	MaintenanceStrategyManual              MaintenanceStrategy = "manual"
	MaintenanceStrategySingle              MaintenanceStrategy = "single"
	MaintenanceStrategyRecurringInterval   MaintenanceStrategy = "recurring-interval"
	MaintenanceStrategyRecurringWeekday    MaintenanceStrategy = "recurring-weekday"
	MaintenanceStrategyRecurringDayOfMonth MaintenanceStrategy = "recurring-day-of-month"
	MaintenanceStrategyCron                MaintenanceStrategy = "cron"
)

func (e MaintenanceStrategy) ToPointer() *MaintenanceStrategy {
	return &e
}
func (e *MaintenanceStrategy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manual":
		fallthrough
	case "single":
		fallthrough
	case "recurring-interval":
		fallthrough
	case "recurring-weekday":
		fallthrough
	case "recurring-day-of-month":
		fallthrough
	case "cron":
		*e = MaintenanceStrategy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MaintenanceStrategy: %v", v)
	}
}
