// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-terraform-provider-ukumawapi/internal/sdk/internal/utils"
)

type MonitorTag struct {
	TagID int64   `json:"tag_id"`
	Value *string `default:"" json:"value"`
}

func (m MonitorTag) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MonitorTag) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MonitorTag) GetTagID() int64 {
	if o == nil {
		return 0
	}
	return o.TagID
}

func (o *MonitorTag) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
