// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NotificationListItem struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Config    string `json:"config"`
	Active    bool   `json:"active"`
	UserID    int64  `json:"userId"`
	IsDefault bool   `json:"isDefault"`
}

func (o *NotificationListItem) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *NotificationListItem) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *NotificationListItem) GetConfig() string {
	if o == nil {
		return ""
	}
	return o.Config
}

func (o *NotificationListItem) GetActive() bool {
	if o == nil {
		return false
	}
	return o.Active
}

func (o *NotificationListItem) GetUserID() int64 {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *NotificationListItem) GetIsDefault() bool {
	if o == nil {
		return false
	}
	return o.IsDefault
}
