// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PublicGroup struct {
	ID          int64                      `json:"id"`
	MonitorList []SchemasStatuspageMonitor `json:"monitorList"`
	Name        string                     `json:"name"`
	Weight      int64                      `json:"weight"`
}

func (o *PublicGroup) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *PublicGroup) GetMonitorList() []SchemasStatuspageMonitor {
	if o == nil {
		return []SchemasStatuspageMonitor{}
	}
	return o.MonitorList
}

func (o *PublicGroup) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PublicGroup) GetWeight() int64 {
	if o == nil {
		return 0
	}
	return o.Weight
}
