// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RegisterUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (o *RegisterUser) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *RegisterUser) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}
