// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SchemasStatuspageMonitor struct {
	ID          int64  `json:"id"`
	Maintenance *bool  `json:"maintenance,omitempty"`
	Name        string `json:"name"`
	SendURL     int64  `json:"sendUrl"`
}

func (o *SchemasStatuspageMonitor) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *SchemasStatuspageMonitor) GetMaintenance() *bool {
	if o == nil {
		return nil
	}
	return o.Maintenance
}

func (o *SchemasStatuspageMonitor) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SchemasStatuspageMonitor) GetSendURL() int64 {
	if o == nil {
		return 0
	}
	return o.SendURL
}
