// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Security struct {
	OAuth2PasswordBearer *string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *Security) GetOAuth2PasswordBearer() *string {
	if o == nil {
		return nil
	}
	return o.OAuth2PasswordBearer
}
