// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type StatusPageList struct {
	Statuspages []StatusPage `json:"statuspages,omitempty"`
}

func (o *StatusPageList) GetStatuspages() []StatusPage {
	if o == nil {
		return nil
	}
	return o.Statuspages
}
