// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Tag struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

func (o *Tag) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Tag) GetColor() string {
	if o == nil {
		return ""
	}
	return o.Color
}
