// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UnpinIncidentResponse struct {
	Detail string `json:"detail"`
}

func (o *UnpinIncidentResponse) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}
