// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-terraform-provider-ukumawapi/internal/sdk/internal/utils"
	"time"
)

// The User model.
type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	LastVisit time.Time `json:"last_visit"`
}

func (u User) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *User) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *User) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *User) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

func (o *User) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *User) GetLastVisit() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.LastVisit
}
