workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    TerraformProviderUkumawapi-OAS:
        inputs:
            - location: /Users/pete.leese/terraform-provider-ukumawapi/openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/terraform-provider-ukumawapi/terraform-provider-ukumawapi/terraform-provider-ukumawapi-oas
targets:
    terraform-provider-ukumawapi:
        target: terraform
        source: TerraformProviderUkumawapi-OAS
