// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pete-leese/terraform-provider-ukumawapi/internal/sdk/models/shared"
)

func (r *StatusPageResourceModel) ToSharedAddStatusPageRequest() *shared.AddStatusPageRequest {
	slug := new(string)
	if !r.Slug.IsUnknown() && !r.Slug.IsNull() {
		*slug = r.Slug.ValueString()
	} else {
		slug = nil
	}
	title := new(string)
	if !r.Title.IsUnknown() && !r.Title.IsNull() {
		*title = r.Title.ValueString()
	} else {
		title = nil
	}
	msg := new(string)
	if !r.Msg.IsUnknown() && !r.Msg.IsNull() {
		*msg = r.Msg.ValueString()
	} else {
		msg = nil
	}
	out := shared.AddStatusPageRequest{
		Slug:  slug,
		Title: title,
		Msg:   msg,
	}
	return &out
}

func (r *StatusPageResourceModel) RefreshFromSharedAddStatusPageResponse(resp *shared.AddStatusPageResponse) {
	if resp != nil {
		r.Msg = types.StringPointerValue(resp.Msg)
	}
}
