// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type MonitorListItem struct {
	AcceptedStatuscodes      []types.String      `tfsdk:"accepted_statuscodes"`
	Active                   types.Int64         `tfsdk:"active"`
	AuthDomain               types.String        `tfsdk:"auth_domain"`
	AuthMethod               types.String        `tfsdk:"auth_method"`
	AuthWorkstation          types.String        `tfsdk:"auth_workstation"`
	BasicAuthPass            types.String        `tfsdk:"basic_auth_pass"`
	BasicAuthUser            types.String        `tfsdk:"basic_auth_user"`
	Body                     types.String        `tfsdk:"body"`
	DatabaseConnectionString types.String        `tfsdk:"database_connection_string"`
	DatabaseQuery            types.String        `tfsdk:"database_query"`
	DNSLastResult            types.String        `tfsdk:"dns_last_result"`
	DNSResolveServer         types.String        `tfsdk:"dns_resolve_server"`
	DNSResolveType           types.String        `tfsdk:"dns_resolve_type"`
	DockerContainer          types.String        `tfsdk:"docker_container"`
	DockerHost               types.String        `tfsdk:"docker_host"`
	ExpiryNotification       types.Bool          `tfsdk:"expiry_notification"`
	Headers                  types.String        `tfsdk:"headers"`
	Hostname                 types.String        `tfsdk:"hostname"`
	ID                       types.Int64         `tfsdk:"id"`
	IgnoreTLS                types.Bool          `tfsdk:"ignore_tls"`
	Interval                 types.Int64         `tfsdk:"interval"`
	Keyword                  types.String        `tfsdk:"keyword"`
	Maxredirects             types.Int64         `tfsdk:"maxredirects"`
	Maxretries               types.Int64         `tfsdk:"maxretries"`
	Method                   types.String        `tfsdk:"method"`
	MqttPassword             types.String        `tfsdk:"mqtt_password"`
	MqttSuccessMessage       types.String        `tfsdk:"mqtt_success_message"`
	MqttTopic                types.String        `tfsdk:"mqtt_topic"`
	MqttUsername             types.String        `tfsdk:"mqtt_username"`
	Name                     types.String        `tfsdk:"name"`
	NotificationIDList       *Notificationidlist `tfsdk:"notification_id_list"`
	Port                     types.Int64         `tfsdk:"port"`
	ProxyID                  types.String        `tfsdk:"proxy_id"`
	PushToken                types.String        `tfsdk:"push_token"`
	RadiusCalledStationID    types.String        `tfsdk:"radius_called_station_id"`
	RadiusCallingStationID   types.String        `tfsdk:"radius_calling_station_id"`
	RadiusPassword           types.String        `tfsdk:"radius_password"`
	RadiusSecret             types.String        `tfsdk:"radius_secret"`
	RadiusUsername           types.String        `tfsdk:"radius_username"`
	ResendInterval           types.Int64         `tfsdk:"resend_interval"`
	RetryInterval            types.Int64         `tfsdk:"retry_interval"`
	Tags                     []types.String      `tfsdk:"tags"`
	Type                     types.String        `tfsdk:"type"`
	UpsideDown               types.Bool          `tfsdk:"upside_down"`
	URL                      types.String        `tfsdk:"url"`
	Weight                   types.Int64         `tfsdk:"weight"`
}
