// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type NotificationListItem struct {
	Active    types.Bool   `tfsdk:"active"`
	Config    types.String `tfsdk:"config"`
	ID        types.Int64  `tfsdk:"id"`
	IsDefault types.Bool   `tfsdk:"is_default"`
	Name      types.String `tfsdk:"name"`
	UserID    types.Int64  `tfsdk:"user_id"`
}
